CREATE TABLE [dbo].[Videos]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1), 
    [Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(200) NULL, 
    [ImageName] NVARCHAR(100) NOT NULL, 
    [Path] NVARCHAR(200) NOT NULL
)
